version: 2
jobs:
  build:
    working_directory: ~/Minaty
    docker:
    - image: circleci/ruby:2.6.0-node-browsers
      environment:
        - RAILS_ENV: 'test'
        - TZ: "Asia/Tokyo"
        
    - image: circleci/mysql:8.0.21
      command: mysqld --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        - MYSQL_ROOT_HOST: '127.0.0.1'

    steps:

    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    - restore_cache:
        keys:
          - rails-demo-yarn-{{ checksum "yarn.lock" }}
          - rails-demo-yarn-

    - run: 
        name: Yarn install
        command: yarn install --cache-folder ~/.cache/yarn

    # Database setup
    - run: mv ./config/database.yml.ci ./config/database.yml

    # Database setup
    - run: 
        name: Databasesetup
        command: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

    - run: bundle exec bin/webpack

    # run tests!

    - run:
        name: Run model rspec
        command: |
          mkdir /tmp/test-results
          bundle exec rspec spec/models -f d \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/model_rspec.xml \

    - run:
        name: Run request rspec
        command: |
          bundle exec rspec spec/requests \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/request_rspec.xml \

    - run:
        name: Run system rspec
        command: |
          bundle exec rspec spec/system \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/system_rspec.xml \
        
    # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
          path: /tmp/test-results
          destination: test-results